name: The Space Race
author: Tucker
baseurl: /space
description: The Cold War Race between the US and the Soviet Union to reach the Moon
github: http://www.github.com/tucker-z
twitter: https://twitter.com/NASA
facebook: https://www.facebook.com/NASA/
linkedin:
email: tzischka17@lvcp.org
location: 0.6875°N   23.4333°E
disqus:

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
